import useMentorWorkspace from '../../../hooks/useMentorWorkspace'
import { EmptyState, MentorCard, MentorIcon, MentorPage, MentorPageHeader, ProgressBar, SectionTitle, StatusPill, menteeName } from '../../../components/mentor/MentorWorkspaceUI'

export default function MentorOutcomes() {
  const { data, loading } = useMentorWorkspace()
  const completedGoals = data.goals.filter((item) => item.status === 'completed')
  const completedSessions = data.sessions.filter((item) => item.status === 'completed')
  const completedActions = data.actions.filter((item) => item.status === 'done')
  const actionRate = data.actions.length ? Math.round(completedActions.length / data.actions.length * 100) : 0
  const averageProgress = data.goals.length ? Math.round(data.goals.reduce((sum, item) => sum + Number(item.progress || 0), 0) / data.goals.length) : 0
  const checkIns = completedSessions.filter((item) => item.check_in)
  const averageCheckIn = checkIns.length ? (checkIns.reduce((sum, item) => sum + Number(item.check_in), 0) / checkIns.length).toFixed(1) : '—'

  return <MentorPage>
    <MentorPageHeader eyebrow="Keyfiyyət və nəticə" title="Rəylər və mentorluq nəticələri" description="Sadəcə ulduz reytinqi yox: məqsəd tərəqqisi, öhdəlik icrası, görüş davamlılığı və mentee check-in nəticələri birlikdə göstərilir." />
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><MentorCard className="p-4"><p className="text-xs text-slate-500">Məqsəd tərəqqisi</p><p className="mt-3 text-2xl font-black text-[#0a2928]">{loading ? '—' : `${averageProgress}%`}</p><div className="mt-3"><ProgressBar value={averageProgress} /></div></MentorCard><MentorCard className="p-4"><p className="text-xs text-slate-500">Öhdəlik icrası</p><p className="mt-3 text-2xl font-black text-[#0a2928]">{actionRate}%</p><div className="mt-3"><ProgressBar value={actionRate} /></div></MentorCard><MentorCard className="p-4"><p className="text-xs text-slate-500">Tamamlanmış sessiya</p><p className="mt-3 text-2xl font-black text-[#0a2928]">{completedSessions.length}</p><p className="mt-1 text-[11px] text-slate-400">Ümumi görüş fəaliyyəti</p></MentorCard><MentorCard className="p-4"><p className="text-xs text-slate-500">Orta check-in</p><p className="mt-3 text-2xl font-black text-[#0a2928]">{averageCheckIn}<span className="text-sm text-slate-400">/5</span></p><p className="mt-1 text-[11px] text-slate-400">Sessiya sonu vəziyyət</p></MentorCard></div>

    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <MentorCard><SectionTitle title="Mentee üzrə nəticə xəritəsi" description="Bu görünüş məlumatı olan münasibətləri müqayisə edir; reytinq yaratmır." /><div className="mt-5 space-y-4">{!data.mentees.length && <EmptyState icon="trend" title="Nəticə məlumatı hələ formalaşmayıb" text="Mentee, məqsəd və sessiya əlavə etdikcə nəticə göstəriciləri burada yaranacaq." />}{data.mentees.map((mentee) => { const goals = data.goals.filter((x) => String(x.mentee_id) === String(mentee.id)); const sessions = data.sessions.filter((x) => String(x.mentee_id) === String(mentee.id) && x.status === 'completed'); const actions = data.actions.filter((x) => String(x.mentee_id) === String(mentee.id)); const progress = goals.length ? Math.round(goals.reduce((sum, x) => sum + Number(x.progress || 0), 0) / goals.length) : 0; const completion = actions.length ? Math.round(actions.filter((x) => x.status === 'done').length / actions.length * 100) : 0; return <article key={mentee.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-sm font-black text-[#087f70]">{menteeName(mentee, 'M').slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#0a2928]">{menteeName(mentee)}</p><p className="mt-1 text-[11px] text-slate-400">{goals.length} məqsəd · {sessions.length} tamamlanmış sessiya</p></div><StatusPill value={progress >= 75 ? 'active' : 'doing'} /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><div className="flex justify-between text-[11px]"><span className="text-slate-500">Məqsəd tərəqqisi</span><b className="text-[#087f70]">{progress}%</b></div><div className="mt-2"><ProgressBar value={progress} /></div></div><div><div className="flex justify-between text-[11px]"><span className="text-slate-500">Öhdəlik icrası</span><b className="text-[#087f70]">{completion}%</b></div><div className="mt-2"><ProgressBar value={completion} /></div></div></div></article>})}</div></MentorCard>
      <div className="space-y-6"><MentorCard><SectionTitle title="Keyfiyyət dövrü" description="Hər 4–6 həftədə qısa refleksiya aparın." /><div className="mt-5 space-y-4">{[['Məqsəd','Hələ də doğrudur və aktualdır?'],['Münasibət','Etibar, təhlükəsizlik və gözlənti aydındır?'],['İcra','Növbəti addımlar vaxtında tamamlanır?'],['Nəticə','Bacarıq, əminlik və ya davranış dəyişir?']].map(([title,text], index) => <div key={title} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-[11px] font-black text-[#087f70]">{index + 1}</span><div><p className="text-xs font-extrabold text-[#0a2928]">{title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{text}</p></div></div>)}</div></MentorCard><MentorCard className="bg-[#f7faf8]"><div className="flex gap-3"><span className="text-[#087f70]"><MentorIcon name="shield" size={21} /></span><div><p className="text-sm font-black text-[#0a2928]">Məxfilik prinsipi</p><p className="mt-2 text-xs leading-5 text-slate-500">Fərdi sessiya qeydləri və həssas məlumatlar ümumi analitikada göstərilmir. Burada yalnız fəaliyyət və nəticə siqnalları toplanır.</p></div></div></MentorCard></div>
    </div>

    <MentorCard><SectionTitle title="Tamamlanmış nəticələr" description="Mentee ilə birlikdə təsdiqlənmiş inkişaf nailiyyətləri." /><div className="mt-5">{!completedGoals.length ? <EmptyState icon="star" title="Tamamlanmış məqsəd yoxdur" text="Məqsəd 100%-ə çatdıqda onu tamamlanmış kimi qeyd edin və nəticəni mentee ilə refleksiya edin." /> : <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{completedGoals.map((goal) => <div key={goal.id} className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"><span className="text-[#087f70]"><MentorIcon name="star" size={18} /></span><p className="mt-3 text-sm font-black text-[#0a2928]">{goal.title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{goal.success_metric || 'Uğur ölçüsü qeyd edilməyib.'}</p></div>)}</div>}</div></MentorCard>
  </MentorPage>
}
