-- Azərbaycan rayonları (Bakı rayon/metro mövcud qalır)
ALTER TABLE service_areas DROP CONSTRAINT IF EXISTS service_areas_kind_check;
ALTER TABLE service_areas
  ADD CONSTRAINT service_areas_kind_check
  CHECK (kind IN ('district', 'metro', 'region'));

INSERT INTO service_areas (id, slug, name_az, kind, sort_order, is_popular) VALUES
  ('abseron', 'abseron', 'Abşeron', 'region', 1010, TRUE),
  ('agcabedi', 'agcabedi', 'Ağcabədi', 'region', 1020, FALSE),
  ('agdam', 'agdam', 'Ağdam', 'region', 1030, FALSE),
  ('agdas', 'agdas', 'Ağdaş', 'region', 1040, FALSE),
  ('agdere', 'agdere', 'Ağdərə', 'region', 1050, FALSE),
  ('agstafa', 'agstafa', 'Ağstafa', 'region', 1060, FALSE),
  ('agsu', 'agsu', 'Ağsu', 'region', 1070, FALSE),
  ('astara', 'astara', 'Astara', 'region', 1080, FALSE),
  ('babek', 'babek', 'Babək', 'region', 1090, FALSE),
  ('balaken', 'balaken', 'Balakən', 'region', 1100, FALSE),
  ('baki', 'baki', 'Bakı', 'region', 1110, TRUE),
  ('barda', 'barda', 'Bərdə', 'region', 1120, FALSE),
  ('beyleqan', 'beyleqan', 'Beyləqan', 'region', 1130, FALSE),
  ('bilesuvar', 'bilesuvar', 'Biləsuvar', 'region', 1140, FALSE),
  ('cebrayil', 'cebrayil', 'Cəbrayıl', 'region', 1150, FALSE),
  ('celilabad', 'celilabad', 'Cəlilabad', 'region', 1160, FALSE),
  ('culfa', 'culfa', 'Culfa', 'region', 1170, FALSE),
  ('dashkasan', 'dashkasan', 'Daşkəsən', 'region', 1180, FALSE),
  ('fuzuli', 'fuzuli', 'Füzuli', 'region', 1190, FALSE),
  ('gedebey', 'gedebey', 'Gədəbəy', 'region', 1200, FALSE),
  ('gence', 'gence', 'Gəncə', 'region', 1210, TRUE),
  ('goranboy', 'goranboy', 'Goranboy', 'region', 1220, FALSE),
  ('goycay', 'goycay', 'Göyçay', 'region', 1230, FALSE),
  ('goygol', 'goygol', 'Göygöl', 'region', 1240, FALSE),
  ('haciqabul', 'haciqabul', 'Hacıqabul', 'region', 1250, FALSE),
  ('imisli', 'imisli', 'İmişli', 'region', 1260, FALSE),
  ('ismayilli', 'ismayilli', 'İsmayıllı', 'region', 1270, FALSE),
  ('kelbecer', 'kelbecer', 'Kəlbəcər', 'region', 1280, FALSE),
  ('kengerli', 'kengerli', 'Kəngərli', 'region', 1290, FALSE),
  ('kurdamir', 'kurdamir', 'Kürdəmir', 'region', 1300, FALSE),
  ('lacin', 'lacin', 'Laçın', 'region', 1310, FALSE),
  ('lenkeran', 'lenkeran', 'Lənkəran', 'region', 1320, TRUE),
  ('lerik', 'lerik', 'Lerik', 'region', 1330, FALSE),
  ('masalli', 'masalli', 'Masallı', 'region', 1340, FALSE),
  ('mingecevir', 'mingecevir', 'Mingəçevir', 'region', 1350, TRUE),
  ('naftalan', 'naftalan', 'Naftalan', 'region', 1360, FALSE),
  ('naxcivan', 'naxcivan', 'Naxçıvan', 'region', 1370, TRUE),
  ('neftcala', 'neftcala', 'Neftçala', 'region', 1380, FALSE),
  ('oguz', 'oguz', 'Oğuz', 'region', 1390, FALSE),
  ('ordubad', 'ordubad', 'Ordubad', 'region', 1400, FALSE),
  ('qebele', 'qebele', 'Qəbələ', 'region', 1410, FALSE),
  ('qax', 'qax', 'Qax', 'region', 1420, FALSE),
  ('qazax', 'qazax', 'Qazax', 'region', 1430, FALSE),
  ('qobustan', 'qobustan', 'Qobustan', 'region', 1440, FALSE),
  ('quba', 'quba', 'Quba', 'region', 1450, FALSE),
  ('qubadli', 'qubadli', 'Qubadlı', 'region', 1460, FALSE),
  ('qusar', 'qusar', 'Qusar', 'region', 1470, FALSE),
  ('saatli', 'saatli', 'Saatlı', 'region', 1480, FALSE),
  ('sabirabad', 'sabirabad', 'Sabirabad', 'region', 1490, FALSE),
  ('salyan', 'salyan', 'Salyan', 'region', 1500, FALSE),
  ('samux', 'samux', 'Samux', 'region', 1510, FALSE),
  ('sederak', 'sederak', 'Sədərək', 'region', 1520, FALSE),
  ('sabran', 'sabran', 'Şabran', 'region', 1530, FALSE),
  ('sahbuz', 'sahbuz', 'Şahbuz', 'region', 1540, FALSE),
  ('seki', 'seki', 'Şəki', 'region', 1550, TRUE),
  ('samaxi', 'samaxi', 'Şamaxı', 'region', 1560, FALSE),
  ('semkir', 'semkir', 'Şəmkir', 'region', 1570, FALSE),
  ('serur', 'serur', 'Şərur', 'region', 1580, FALSE),
  ('sirvan', 'sirvan', 'Şirvan', 'region', 1590, FALSE),
  ('siyezen', 'siyezen', 'Siyəzən', 'region', 1600, FALSE),
  ('susa', 'susa', 'Şuşa', 'region', 1610, FALSE),
  ('sumqayit', 'sumqayit', 'Sumqayıt', 'region', 1620, TRUE),
  ('terter', 'terter', 'Tərtər', 'region', 1630, FALSE),
  ('tovuz', 'tovuz', 'Tovuz', 'region', 1640, FALSE),
  ('ucar', 'ucar', 'Ucar', 'region', 1650, FALSE),
  ('xacmaz', 'xacmaz', 'Xaçmaz', 'region', 1660, FALSE),
  ('xankendi', 'xankendi', 'Xankəndi', 'region', 1670, FALSE),
  ('xizi', 'xizi', 'Xızı', 'region', 1680, FALSE),
  ('xocali', 'xocali', 'Xocalı', 'region', 1690, FALSE),
  ('xocavend', 'xocavend', 'Xocavənd', 'region', 1700, FALSE),
  ('yardimli', 'yardimli', 'Yardımlı', 'region', 1710, FALSE),
  ('yevlax', 'yevlax', 'Yevlax', 'region', 1720, FALSE),
  ('zaqatala', 'zaqatala', 'Zaqatala', 'region', 1730, FALSE),
  ('zengilan', 'zengilan', 'Zəngilan', 'region', 1740, FALSE),
  ('zerdab', 'zerdab', 'Zərdab', 'region', 1750, FALSE)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name_az = EXCLUDED.name_az,
  kind = EXCLUDED.kind,
  sort_order = EXCLUDED.sort_order,
  is_popular = EXCLUDED.is_popular;
