import { Link } from 'react-router-dom'
import useAuthStore from '../../hooks/useAuth'
import useMentorWorkspace from '../../hooks/useMentorWorkspace'
import { EmptyState, formatDate, MentorCard, MentorIcon, MentorPage, MentorPageHeader, Metric, ProgressBar, SectionTitle, StatusPill, menteeName } from '../../components/mentor/MentorWorkspaceUI'

export default function MentorDashboard() {
  const { user } = useAuthStore()
  const { data, loading, error } = useMentorWorkspace()
  const hour = new Date().getHours()
  const greeting = hour < 12 ? 'Sabahınız xeyir' : hour < 18 ? 'Günortanız xeyir' : 'Axşamınız xeyir'
  const firstName = user?.full_name?.trim()?.split(/\s+/)[0] || 'Mentor'
  const activeGoals = data.goals.filter((item) => item.status === 'active')
  const plannedSessions = data.sessions.filter((item) => item.status === 'planned').sort((a, b) => new Date(a.scheduled_at || 0) - new Date(b.scheduled_at || 0))
  const openActions = data.actions.filter((item) => item.status !== 'done')
  const completedActions = data.actions.filter((item) => item.status === 'done')
  const actionRate = data.actions.length ? Math.round(completedActions.length / data.actions.length * 100) : 0
  const averageProgress = activeGoals.length ? Math.round(activeGoals.reduce((sum, goal) => sum + Number(goal.progress || 0), 0) / activeGoals.length) : 0
  const nextActions = [
    !data.services.length && { title: 'İlk mentorluq təklifini yarat', text: 'Kimə, hansı nəticəni və hansı formatda verdiyinizi aydınlaşdırın.', to: '/instructor/teaching-groups', icon: 'box' },
    !activeGoals.length && { title: 'İlk SMART məqsədi qur', text: 'Mentee ilə ölçülən nəticə və yol xəritəsi müəyyənləşdirin.', to: '/instructor/roadmap', icon: 'target' },
    !plannedSessions.length && { title: 'Mentorluq sessiyası planla', text: 'Gündəliyi və gözlənilən nəticəni görüşdən əvvəl yazın.', to: '/instructor/schedule', icon: 'calendar' },
    openActions.length > 0 && { title: `${openActions.length} açıq öhdəliyi nəzərdən keçir`, text: 'Məsul tərəf və son tarix üzrə icranı yoxlayın.', to: '/instructor/tasks', icon: 'check' },
  ].filter(Boolean).slice(0, 3)

  return <MentorPage>
    <MentorPageHeader eyebrow="Mentor kabineti" title={`${greeting}, ${firstName}`} description="Bugünkü prioritetləri, mentee tərəqqisini və növbəti mentorluq addımlarını bir yerdən idarə edin." action={<Link to="/instructor/schedule" className="inline-flex items-center gap-2 rounded-xl bg-[#087f70] px-4 py-2.5 text-xs font-extrabold text-white shadow-sm hover:bg-[#06685d]"><MentorIcon name="plus" size={15} /> Sessiya planla</Link>} secondary={<Link to="/instructor/roadmap" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 hover:border-[#087f70] hover:text-[#087f70]"><MentorIcon name="target" size={15} /> Məqsəd yarat</Link>} />
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs font-semibold text-rose-700">{error}</div>}

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Aktiv mentee-lər" value={loading ? '—' : data.mentees.length} note="Davam edən münasibətlər" icon="users"/><Metric label="Aktiv məqsədlər" value={loading ? '—' : activeGoals.length} note={`${averageProgress}% orta tərəqqi`} icon="target"/><Metric label="Növbəti sessiyalar" value={loading ? '—' : plannedSessions.length} note="Planlaşdırılmış görüşlər" icon="calendar"/><Metric label="Öhdəlik icrası" value={loading ? '—' : `${actionRate}%`} note={`${openActions.length} açıq addım`} icon="trend"/></div>

    <div className="grid gap-6 xl:grid-cols-[1.12fr_.88fr]">
      <MentorCard><SectionTitle title="Bu gün nə tələb edir?" description="Workspace real məlumatlara görə növbəti ən faydalı addımı göstərir." /><div className="mt-5 space-y-3">{!nextActions.length ? <div className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-5"><div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#087f70] text-white"><MentorIcon name="check" size={17} /></span><div><p className="text-sm font-black text-[#0a2928]">Əsas mentorluq axınınız qurulub</p><p className="mt-1 text-xs leading-5 text-slate-500">Məqsəd və sessiyaları mentee ilə müntəzəm yeniləyin.</p></div></div></div> : nextActions.map((item, index) => <Link key={item.title} to={item.to} className="group flex items-start gap-4 rounded-xl border border-slate-200 p-4 transition hover:border-[#087f70]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-[#087f70]"><MentorIcon name={item.icon} size={18} /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-[10px] font-black text-slate-350">0{index + 1}</span><p className="text-sm font-black text-[#0a2928]">{item.title}</p></div><p className="mt-1 text-xs leading-5 text-slate-500">{item.text}</p></div><span className="mt-2 text-[#087f70] transition group-hover:translate-x-1"><MentorIcon name="arrow" size={15} /></span></Link>)}</div></MentorCard>
      <MentorCard><SectionTitle title="Mentorluq sağlamlığı" description="Məqsəd, sessiya və öhdəliklərin balansı." /><div className="mt-6 space-y-5">{[['Məqsəd tərəqqisi', averageProgress],['Öhdəlik icrası', actionRate],['Razılaşma əhatəsi', data.mentees.length ? Math.round(data.agreements.filter((x) => x.status === 'accepted').length / data.mentees.length * 100) : 0]].map(([label,value]) => <div key={label}><div className="flex justify-between text-xs"><span className="font-semibold text-slate-500">{label}</span><span className="font-black text-[#087f70]">{value}%</span></div><div className="mt-2"><ProgressBar value={value} /></div></div>)}</div><Link to="/instructor/analytics" className="mt-6 inline-flex items-center gap-1 text-xs font-extrabold text-[#087f70]">Nəticələri detallı gör <MentorIcon name="arrow" size={13} /></Link></MentorCard>
    </div>

    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
      <MentorCard><SectionTitle title="Növbəti sessiyalar" description="Görüşdən əvvəl gündəlik və açıq öhdəlikləri yoxlayın." action={<Link to="/instructor/schedule" className="text-xs font-extrabold text-[#087f70]">Cədvəli aç</Link>} /><div className="mt-5 space-y-3">{!plannedSessions.length && !loading && <EmptyState icon="calendar" title="Sessiya planlaşdırılmayıb" text="Məqsədə bağlı ilk görüşü planlaşdırın və gündəlik yaradın." action="Sessiya səhifəsinə keç" link="/instructor/schedule" />}{plannedSessions.slice(0, 3).map((session) => <Link to="/instructor/schedule" key={session.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4 hover:border-[#087f70]"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-[#087f70]"><MentorIcon name="calendar" size={18} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#0a2928]">{session.title}</p><p className="mt-1 text-[11px] text-slate-400">{formatDate(session.scheduled_at)} · {menteeName(data.mentees.find((x) => String(x.id) === String(session.mentee_id)))}</p></div><StatusPill value={session.status} /></Link>)}</div></MentorCard>
      <MentorCard><SectionTitle title="Açıq öhdəliklər" description="Sessiyalar arasında inkişafı hərəkətdə saxlayan addımlar." action={<Link to="/instructor/tasks" className="text-xs font-extrabold text-[#087f70]">Hamısını aç</Link>} /><div className="mt-5 space-y-3">{!openActions.length && <EmptyState icon="check" title="Açıq öhdəlik yoxdur" text="Sessiya sonunda bir konkret növbəti addım yaradın." />}{openActions.slice(0, 4).map((action) => <div key={action.id} className="flex items-start gap-3"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-slate-200"/><div><p className="text-xs font-bold text-slate-700">{action.title}</p><p className="mt-1 text-[10px] text-slate-400">{action.owner_type === 'mentor' ? 'Mentor' : action.owner_type === 'shared' ? 'Birgə' : 'Mentee'} · {formatDate(action.due_date)}</p></div></div>)}</div></MentorCard>
    </div>

    <MentorCard><SectionTitle title="Aktiv məqsədlər" description="Hər sessiyanın məqsədlə əlaqəsi mentorluğun təsirini ölçülə bilən edir." action={<Link to="/instructor/roadmap" className="text-xs font-extrabold text-[#087f70]">Yol xəritəsinə bax</Link>} /><div className="mt-5 grid gap-4 lg:grid-cols-3">{!activeGoals.length && <div className="lg:col-span-3"><EmptyState icon="target" title="Aktiv məqsəd yoxdur" text="Bir-üç konkret SMART məqsədlə mentorluq istiqamətini yaradın." action="Məqsəd səhifəsinə keç" link="/instructor/roadmap" /></div>}{activeGoals.slice(0, 3).map((goal) => <article key={goal.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-2"><StatusPill value={goal.status} /><span className="text-sm font-black text-[#087f70]">{goal.progress}%</span></div><p className="mt-3 text-sm font-black text-[#0a2928]">{goal.title}</p><p className="mt-1 text-[11px] text-slate-400">{menteeName(data.mentees.find((x) => String(x.id) === String(goal.mentee_id)))}</p><div className="mt-4"><ProgressBar value={goal.progress} /></div></article>)}</div></MentorCard>
  </MentorPage>
}
